#!/bin/bash


if [[ $# -eq 0 ]] ; then
    echo 'input file missing'
    echo 'run: AddEpochCal input_file.csv epoch_cal_file.txt'
    echo 'input_file format header: CODE|SB_name|Band|Config|[Epoch]|SB_list_date|[SB_STATE]'

    exit 1
fi

# Epoch Example: TRANSIT-1h,2020-09-12 

this_file=$0

YMD=$(date +%y%m%d-%H%M%S)


# input list file of SBs

SB_list_file=$1

epoch_cal_file=$2

echo "SB list file = $SB_list_file"

echo "epoch cal file = $epoch_cal_file"



# name for new input file with added epochs

new_SB_list_file=${SB_list_file}_multiepoch.csv

# touch $new_SBs_list_file


# header of output file

echo "CODE|sbName|band|nominalConf|epoch|sb_list_date|SB_STATE" > $new_SB_list_file



# read and save calendar in array

epoch_calendar=()

while IFS= read -r line; do

    # echo $line

    epoch_calendar+=("$line")

done < $epoch_cal_file


# read input list of SBs

# line counter

l=0

while IFS='|' read -r col1 col2 col3 col4 col5 col6 col7
do 
    
    # skip first line with header

    test $l -eq 0 && ((l=l+1)) && continue

    # read SB list info

    CODE=$col1
    SB_name=$col2
    Band=$col3
    conf=$col4
    Epoch=$col5
    sb_list_date=$col6
    sb_state=$col7
	    
    # save SB in new input file using all dates in calendar file 
	    
    for i in "${epoch_calendar[@]}"
    do
	
	Epoch=$i

	echo "$CODE|$SB_name|$Band|$conf|$Epoch|$sb_list_date|$sb_state" >> $new_SB_list_file
    done
    
done < $SB_list_file
